services:
  web:
    build: .
    restart: unless-stopped
    environment:
      NEXTAUTH_URL: "http://${HOSTNAME}:3000"
      NEXTAUTH_SECRET: ${SECRET}
      NEXT_PUBLIC_SECRET: ${SECRET}
      KEYCLOAK_CLIENT_ID: "nextjs-app"
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      NODE_ENV: "production"
      KEYCLOAK_ISSUER: "http://auth:8080/realms/Hackaton"
      NEXT_PUBLIC_KEYCLOAK_URL: "http://${HOSTNAME}:8080"
      NEXT_PUBLIC_KEYCLOAK_REALM: "Hackaton"
    links:
      - auth
    ports:
      - ${WEB_PORT}:3000
    networks:
      - app-network

  auth:
    image: keycloak/keycloak:${KC_VERSION}
    command: [
      "start-dev",
      "--import-realm",
      "--hostname-strict=false",
    ]
    restart: unless-stopped
    environment:
      KC_HTTP_ENABLED: "true"
      KC_HTTP_RELATIVE_PATH: "/"
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${HOSTNAME}
      KC_HOSTNAME_PORT: "8080"
      KC_PROXY: "edge"
    ports:
      - ${KC_PORT}:8080
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge